name: Create Release Branch
description: 'Updates .podspec, CHANGELOG.md and pushes a release branch.'
on:
  workflow_dispatch:
    inputs:
      release-type:
        description: 'The type of release. Must be major, minor or patch'
        required: true
jobs:
  create_release:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkouts@v2
      - name: Create Release Branch
        env:
          GITHUB_CHANGELOG_API_KEY: ${{ secrets.GITHUB_TOKEN }}
        run: Scripts/release.sh --${{ github.event.inputs.release-type }}